jump-dev/SCS.jl

- src/SCSSolverInterface.jl
- test/mpb_conic.jl
All Convex.jl tests also continue to pass. Fixes #8. Can be made more efficient.
> Add symmetry constraints for SCS

- deps/build.jl
- src/SCS.jl
- test/runtests.jl
pretty sure there's been a tag since this was added
> shouldn't need to do Pkg.checkout("MathProgBase") any more

- deps/build.jl
note - not tested locally yet, just built and uploaded so far
> Use v1.1.5 and update windows binary checksums accordingly

- README.md
- src/low_level_wrapper.jl
just a wrapper around the ccall to scs_version.
SCS_version() returns ASCIIString, e.g. "1.1.4"
> expose SCS_version() method

- deps/build.jl
slightly roundabout way of doing this that doesn't need Compat
> fix deprecation warning in deps/build.jl

- .travis.yml
- REQUIRE
- appveyor.yml
- deps/build.jl
raise REQUIRE to 0.4.0-rc4 (so do bump minor package version when this gets tagged), adjust travis and appveyor accordingly
closes #45
> Rebuild Windows binaries for new 64_ openblas suffix

- REQUIRE
- deps/build.jl
- src/SCS.jl
- src/SCSSolverInterface.jl
- src/types.jl
- src/version.jl
Need to tag soon since homebrew already has 1.1.8.
CC @tkelman
> bump source to 1.1.8; remove dependency on compat

- src/SCS.jl
- src/SCSSolverInterface.jl
- test/mpb_linear.jl
- test/options.jl
Ref JuliaOpt/MathProgBase.jl#91
Don't merge until new MPB is about to be released.
> updates for MPB 0.4

- REQUIRE
- src/SCSSolverInterface.jl
- test/runtests.jl
Pretty simple change. Ref https://github.com/JuliaOpt/MathProgBase.jl/pull/108
CC @chriscoey @madeleineudell 
Fixes #50 
Closes #51
> update for new SDP format

- src/SCSSolverInterface.jl
Ref https://github.com/JuliaOpt/MathProgBase.jl/pull/110
CC @chriscoey
> implement getvardual interface

- src/SCS.jl
`@unix_only` to `if is_unix()`
> Fix depwarn in init function

- .travis.yml
- appveyor.yml
> won't be needing nightly on this branch

- src/SCSSolverInterface.jl
> implement getsolvetime

- deps/build.jl
Now working on windows again. Update the tags to the latest release.
> Bump to v2.0.2

- .travis.yml
- REQUIRE
- src/MOIWrapper.jl
When MOI is released, the change in `.travis.yml` can be rolled back and then we can merge.
> Update for MOI v0.3

- REQUIRE
- appveyor.yml
- src/MOIWrapper.jl
- test/MOIWrapper.jl
and replace the appveyor script with [the new one](https://discourse.julialang.org/t/ann-improved-appveyor-scripts/12754)
> Update to MOI v0.5

- src/MOIWrapper.jl
- test/MOIWrapper.jl
Closes https://github.com/JuliaOpt/SCS.jl/issues/115
> Add support and tests SingleVariable objective

- README.md
The current instruction can lead to the confusion discussed in https://github.com/JuliaOpt/SCS.jl/issues/117#issuecomment-430348352
@jzazo Does the new README make it clearer ?
> Clarify manual installation

- src/MOIWrapper.jl
It is implemented in the same way in the MPB wrapper
> Implement MOI.SolveTime

- src/MOI_wrapper.jl
Follows #129 
Thanks @blegat !
> Support (dual) power cones

- REQUIRE
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/JuliaOpt/SCS.jl/issues/131
Closes https://github.com/JuliaOpt/SCS.jl/issues/132
>  Simplify thanks to Vectorize and NonpostoNonneg bridges

- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/JuliaOpt/SCS.jl/issues/133
> Remove support for VectorOfVariables and run psds and qcp tests

- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Support string values in RawParameter

- .travis.yml
- Project.toml
- src/SCS.jl
x-ref: https://github.com/JuliaPackaging/Yggdrasil/issues/509#issuecomment-605516668
> Use jll for Julia 1.3 and higher

- src/MOI_wrapper.jl
See https://github.com/jump-dev/SCS.jl/issues/181
> Replace sparse by canonical

- src/MOI_wrapper.jl
- src/c_wrapper.jl
- src/geometric.jl
- src/matrix.jl
- src/types.jl
- test/MOI_wrapper.jl
- test/runtests.jl
Closes https://github.com/jump-dev/SCS.jl/issues/186
> Directly store the sparse matrix in the SCS format

- .buildkite/pipeline.yml
- .gitlab-ci.yml
- test/runtests.jl
Closes #201 
TODO: Complete steps https://github.com/JuliaGPU/buildkite#adding-a-repository
Also TODO:
> Add buildkite CI for GPU

- README.md
- test/test_gpu.jl
the new version bumps cuda to 10.1
> update README for scs-2.1.3

- .JuliaFormatter.toml
- .github/workflows/format_check.yml
- src/MOI_wrapper.jl
- src/SCS.jl
- src/c_wrapper.jl
- src/c_wrapper_gpu.jl
- src/geometric.jl
- src/matrix.jl
- src/types.jl
- test/MOI_wrapper.jl
- test/runtests.jl
- test/test_gpu.jl
- test/test_problems.jl
> Add JuliaFormatter

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Throw UnsupportedConstraint

- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI_wrapper.jl
> Add primal/dual warm starts

- README.md
- src/c_wrapper.jl
> Revise low-level documentation

- Project.toml
- src/MOI_wrapper/MOI_wrapper.jl
- test/MOI_wrapper.jl
- test/runtests.jl
> Fix implementation of PowerCones

- src/MOI_wrapper/MOI_wrapper.jl
- src/c_wrapper.jl
- test/MOI_wrapper.jl
See https://github.com/jump-dev/ECOS.jl/pull/135 for the motivation and original test.
> Add checks for an invalid model

- LICENSE.md
- src/MOI_wrapper/MOI_wrapper.jl
- src/MOI_wrapper/scaled_psd_cone_bridge.jl
- src/SCS.jl
- src/c_wrapper.jl
- src/linear_solvers/direct.jl
- src/linear_solvers/gpu_indirect.jl
- src/linear_solvers/indirect.jl
- test/MOI_wrapper.jl
- test/runtests.jl
- test/test_gpu.jl
- test/test_problems.jl
x-ref https://github.com/jump-dev/AmplNLWriter.jl/pull/155
> Add copyright headers

- Project.toml
- test/MOI_wrapper.jl
Failing because of https://github.com/jump-dev/MathOptInterface.jl/issues/2175
> Add test for bridge

- Project.toml
- src/SCS.jl
x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2643
> Add PrecompileTools.jl

- src/MOI_wrapper/MOI_wrapper.jl
When I wrotet this hacky direct access to the `num_rows` field, there wasn't this `num_rows` function yet
> Use MOI.Utilities.num_rows

- src/MOI_wrapper/hermitian_complex_psd_cone_bridge.jl
> add dedicated set_dot method for CanonicalVector
