jump-dev/SCS.jl

deps/build.jl
src/SCS.jl
test/direct.jl

We hadn't been testing the SCS functionality which calls lapack, oops.
@tkelman @staticfloat, is this a reasonable fix? Not sure how else to enable SCS to find julia's lapack symbols. It should be safe to load these globally now that the 64-bit integer API won't cause name clashes.
CC @karanveerm

explicitly load lapack with RTLD_GLOBAL

---

REQUIRE
src/high_level_wrapper.jl
src/types.jl

cc @madeleineudell @davidlizeng @jennyhong 
Throughout [EE364A](http://web.stanford.edu/class/ee364a/), we have been running into issues where the problem solution is inaccurate because max_iters has been too small (and also outside of EE364A: https://github.com/JuliaOpt/Convex.jl/issues/64 or [time series](http://nbviewer.ipython.org/github/JuliaOpt/Convex.jl/blob/master/examples/time_series/time_series.ipynb)).
Prof. Boyd really wants us to make `max_iters` 20k by default and change `eps` to `1e-4`. 
Also get rid of deprec warning.

Update max_iters + fix deprec warning

---

src/SCSSolverInterface.jl

Now output in https://github.com/JuliaOpt/SCS.jl/issues/40 is:
```
julia> @show MathProgBase.status(m)
MathProgBase.status(m) = :Optimal
:Optimal
julia> @show MathProgBase.getobjval(m)
MathProgBase.getobjval(m) = -0.0005944812927751632
-0.0005944812927751632
julia> @show MathProgBase.getsolution(m)
MathProgBase.getsolution(m) = [-0.0005944812927751632,1.0000244304176664,1.000024520748117]
3-element Array{Float64,1}:
-0.000594481
1.00002    
1.00002    
julia> y = MathProgBase.getconicdual(m)
5-element Array{Float64,1}:
1663.68
1663.68
1663.68
1.0 
-1663.68
julia> @show y
y = [1663.6755938289195,1663.676176978334,1663.6760356732946,1.0000001698583723,-1663.675735133884]
5-element Array{Float64,1}:
1663.68
1663.68
1663.68
1.0 
-1663.68
julia> @show -dot(b,y) # should match primal objective …
```

take out sign flipping, closes #40

---

src/SCSSolverInterface.jl

Fix warnings due to deprecated use of 'int()' instead of 'round(Int,)'

---

deps/build.jl

`-m32` and `-m64` are for getting different architecture binaries from a multilib compiler
Julia can use either 32 or 64 bit integers in blas on 64 bit, these aren't coupled

don't mix blas integer size and binary word size

---

src/SCS.jl

All Linux installs with SCS 1.1 are broken as of the last release:
```
julia> using SCS
ERROR: InitError: UndefVarError: depsdir not defined
in __init__() at /home/mlubin/.julia/v0.5/SCS/src/SCS.jl:24
in _include_from_serialized(::String) at ./loading.jl:150
in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
in require(::Symbol) at ./loading.jl:371
during initialization of module SCS
```
@kalmarek, please test changes like this.

fix broken warning

---

README.md
deps/build.jl
src/SCS.jl
src/high_level_wrapper.jl
src/types.jl

SCS 2.0 makes several changes, but the main one that interfaces need to be aware of is the addition of a new field in the settings called `acceleration_lookback` which is the number of iterates that SCS will keep in memory in order to do an acceleration extrapolation step. Due to the acceleration step SCS 2.0 is in general faster than SCS 1.*, and consequently has tightened the default tolerance from 1e-3 to 1e-5.
Merging this will require re-uploading new binaries for all platforms, if I understand the distribution process correctly.

Update interface for SCS 2.0.0

---

src/SCSSolverInterface.jl
src/high_level_wrapper.jl
test/direct.jl
test/runtests.jl

This PR deprecates the arguments `qsize`, `ssize` and `psize`. These indicate the length of the vectors `q`, `s` and `p` in C but they are not necessary in Julia as the length can be queried from the vector.
Having a separate length is therefore redundant and could potentially create bugs very difficult to debug for the user.
I have create methods without the argument and in old methods, I have added a deprecation warning with `@assert` to check that the size argument is indeed the size of the vector. This is in case a user have a longer vector and actually needs the rest of the vector to be ignore and therefore depends on the feature. This user will get an assert error which indicates he is doing something wrong.

Remove deprecate size argument for cones

---

src/types.jl

Alpha of 1.5 has been the default in SCS for a while, because for some problems 1.8 can be too aggressive. See the discussion here: https://github.com/JuliaOpt/MathOptInterfaceSCS.jl/issues/1#issuecomment-350217337

reduce alpha to 1.5

---

src/MOIWrapper.jl

@ccoffrin Can you test it and report whether it works as expected for your use case ?
Closes https://github.com/JuliaOpt/SCS.jl/issues/109

Add support for starting values

---

test/MOIWrapper.jl

This line was written when the `RSOC` bridge was not implemented yet.

✅ Add RootDet, GeoMean and RSOC tests

---

REQUIRE
test/MOIWrapper.jl

It was resolved in https://github.com/JuliaOpt/MathOptInterface.jl/pull/537

✅ Enable solve_blank_obj fixed in MOI v0.6.2

---

test/MOIWrapper.jl
test/MPBWrapper.jl

When there are failures in the tests, they get drowned by the SCS log.

Use verbose=0 for MPB and MOI tests

---

src/MOI_wrapper.jl

Closes https://github.com/JuliaOpt/SCS.jl/issues/136

Fix start value

---

src/MOI_wrapper.jl

While running against JuMP examples on https://github.com/JuliaOpt/JuMP.jl/pull/2003 , the following error appeared and tests successfully with this PR.
```julia
robust_uncertainty.jl: Error During Test at /home/coroa/.julia/dev/JuMP/examples/run_examples.jl:20
Got exception outside of a @test
LoadError: MethodError: load_constraint(::SCS.Optimizer, ::MathOptInterface.ConstraintIndex{MathOptInterface.VectorAffineFunction{Float64},MathOptInterface.SecondOrderCone}, ::MathOptInterface.VectorAffineFunction{Float64}, ::MathOptInterface.SecondOrderCone) is ambiguous. Candidates:
load_constraint(optimizer::SCS.Optimizer, ci, f::MathOptInterface.VectorAffineFunction, s::MathOptInterface.AbstractVectorSet) in SCS at /home/coroa/.julia/packages/SCS/RkVe4/src/MOI_wrapper.jl:280 …
```

Fix method ambiguity of MOIU.load_constraint

---

.travis.yml

We can still see the outcome, but GitHub does not consider it a failed test.
I think this makes sense, since Julia 1.2 is not released yet?

Allow CI failure with Julia 1.2

---

.gitignore
.travis.yml
Project.toml
README.md
REQUIRE
appveyor.yml
src/MOI_wrapper.jl
src/MPB_wrapper.jl
src/SCS.jl
src/c_wrapper.jl
src/types.jl
test/MOI_wrapper.jl
test/MPB_wrapper.jl
test/mpb_linear.jl
test/runtests.jl
test/test_problems.jl

Also drop Julia v0.6, Julia v0.7 and transition from REQUIRE to Project.toml.

Updates to MOI v0.9

---

src/MOI_wrapper.jl

Forgot to add to the `support_constraint` function, it is probably better to wait for MOI to have the tests for DualExponentialCone https://github.com/JuliaOpt/MathOptInterface.jl/pull/873.

Fix support constraint for DualExponentialCone

---

src/MOI_wrapper.jl

The fields in the SCS struct are in milliseconds. The SolveTime
attribute is in seconds.
https://github.com/cvxgrp/scs/blob/e5bb794ac014b7a86d127ac03651d2c8a12ecba8/include/scs.h#L98

Fix solve_time computation

---

src/MOI_wrapper.jl
test/MOI_wrapper.jl

About naming the attribute: SCS does multiple kinds of iterations, e.g., ADMM iterations (main outer iterations) and CG iterations (inner iterations, in indirect mode only), so being specific seems reasonable. It's not obvious that this could or should be covered by a new MOI attribute, so I made it specific to SCS.

expose the number of iterations as an MOI attribute

---

src/MOI_wrapper.jl

I was trying to solve some SDPs with quite large `MOI.PositiveSemidefiniteConeTriangle` constraints and noticed that copying the problem into SCS format took unusually long (>5min).
I narrowed the problem down to the `_scalecoef` function:
https://github.com/JuliaOpt/SCS.jl/blob/bd8ef05828e434f17630442de9a812abf6ee7604/src/MOI_wrapper.jl#L263-L276
The way `diagidx` is assembled seems to cause performance problems. We fixed that issue in `COSMO`'s MOI-wrapper in the following way: 
https://github.com/oxfordcontrol/COSMO.jl/pull/87
I shamelessly copied @nrontsis fix. The fix reduces the time to assemble a large SDP to a few seconds.
You can use the following code to check this:
```julia
using MathOptInterface, SCS, Random, LinearAlgebra, SparseArrays, Random
const MOI = MathOptInterface …
```

Fix performance bottleneck in _scalecoeff

---

src/MOI_wrapper.jl

SCS does not exploit the specific structure of a SingleVariable objective, the MOI wrapper just hardcodes the `Objective.FunctionizeBridge`. It should instead not support it.

Remove support for SingleVariable objective function

---

src/MOI_wrapper.jl

As correctly noted in the `#FIXME comment` the scaling method `scale_coeff` assumes an upper triangular input (triangular numbers yield the diagonal entries of upper triangular elements of a matrix). Therefore, we have to keep the right order with scaling and transforming:
1. Scale, then transform U->L
2. Transform L->U, then unscale
I probably introduced that bug myself in #165. I noticed this when comparing the output of `JuMP + SCS` vs. `SCS.Direct`. I am not sure, why the unit tests didn't catch it.

Scale off-diagonals of b before transforming U -> L

---

src/MOI_wrapper.jl

Passing parameters through the constructor triggered a deprecation warning about MOI.RawParameter, which is not helpful for users.
CC @odow @blegat

Fix extraneous deprecation warning

---

src/types.jl

If we are able to directly generate these three vectors from the MOI wrapper and directly call the constructor, it would spare these copies.

Allow creation of ManagedMatrix without copy of vectors

---

src/types.jl

Copying the problem data is expensive and should be avoided when possible. It's definitely not needed in this context.

remove unnecessary copy

---

src/MOI_wrapper.jl

Without specifying `m`, and `n`, sparse can return a matrix of the wrong dimensions if there are empty columns or rows. In particular for CSC matrices, this could cause a crash if the last column is empty.

Safer call to sparse()

---

deps/build.jl

Looking properly at issue https://github.com/jump-dev/SCS.jl/issues/194#issue-673098930, I have realized it is not a problem with `SCS.jl`. The reason for failure to install is caused simply by running unsupported Julia binaries -- such as those linked against OpenBLAS different from the one used by `scsindir.so` from BinaryProvider.
While this is **clearly** mentioned in `README.md`, when a user tries to install `SCS.jl` the easy way first, they get: 
```
ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/home/user/.julia/packages/SCS/28Svy/deps/usr)") is not satisfied, cannot generate deps.jl!
```
At this point, it is not obvious that it is the users fault.
The user could try to debug the problem by adding `--verbose` to `ARGS`. They would, unfortunately, not …

Explain why installation failed for users with incompatible Julia binary

---

src/types.jl
test/options.jl

> I think the direct solver should be the default solver used everywhere unless the problem is so large that only the indirect solver can handle it.
https://github.com/jump-dev/SCS.jl/pull/205#issuecomment-791938069

make DirectSolver the default one

---

src/geometric.jl

We're calling `copy_to` to this `GeometricConicForm` directly:
https://github.com/jump-dev/SCS.jl/blob/7669c8df10a71da367e6bf7fe37a3ee7aba144a1/src/MOI_wrapper.jl#L146
so it needs to implement `supports` otherwise the starting values are not copied and we get the warning
```
┌ Warning: MathOptInterface.VariablePrimalStart() is not supported by SCS.GeometricConicForm{Float64, SCS.SparseMatrixCSRtoCSC{Int64}, NTuple{8, DataType}}. This information will be discarded.
```

Conic form supports variable primal

---

Project.toml
src/MOI_wrapper/scaled_psd_cone_bridge.jl
test/MOI_wrapper.jl

Closes #224 
The `SetMap` bridges are set up in MOI such that the bridge should accept any incoming function type. That means that this wasn't getting `functionized` in between.
I looked at changing things on the MOI end, but it was easier to just add support here.

Fix VectorOfVariables-in-PositiveSemidefiniteConeTriangle

---

src/MOI_wrapper/MOI_wrapper.jl

Updated for https://github.com/jump-dev/MathOptInterface.jl/pull/1660
<s>Tests will fail because of https://github.com/jump-dev/MathOptInterface.jl/pull/1656#issuecomment-972125589</s> Only on `master`, not 0.10.5.
Opened upstream: https://github.com/cvxgrp/scs/issues/185

Fix objective values for certificates

---

src/MOI_wrapper/MOI_wrapper.jl

We should only tell SCS to warm-start the solve if the user has explicitly passed one.
Closes #241

Only pass warm-start if explicitly set

---

src/SCS.jl

See https://github.com/jump-dev/ECOS.jl/pull/134
There's no performance penalty to using `global` because they are only evaluated in the ccall once.

Set library path in __init__

---

Project.toml

SCS_jll@v3.2.0 is a breaking release so it's causing a segfault in the JuMP documentation: https://github.com/jump-dev/JuMP.jl/pull/2900

Fix SCS_jll@v3.0.0 to avoid breaking v3.2.0 release

---

Project.toml
README.md
src/SCS.jl
src/linear_solvers/direct.jl
src/linear_solvers/gpu_indirect.jl
src/linear_solvers/indirect.jl
src/linear_solvers/mkl_direct.jl
test/MOI_wrapper.jl
test/runtests.jl

this is a proof of concept, depends on https://github.com/JuliaPackaging/Yggdrasil/pull/4773 but works locally ;)
Besides `MKLDirectSolver` I've added runtime `scs_version` for each solver library; 
@odow technically it's a breaking change (there is argumentless version anymore), but it was just internal function that we didn't even test. So maybe we should ask do we actually need to query for version at runtime?

add support for sparse-direct-mkl-pardiso solver

---

src/c_wrapper.jl
test/MOI_wrapper.jl

x-ref https://github.com/jump-dev/JuMP.jl/pull/3402

Fix flush of stdout after solve

---

src/MOI_wrapper/MOI_wrapper.jl

Add support for ObjectiveFunction{ScalarQuadraticFunction}

---

Project.toml
src/MOI_wrapper/scaled_psd_cone_bridge.jl

See https://github.com/jump-dev/MathOptInterface.jl/issues/2260

Update to the new MOI scaled set

---

Project.toml

We need the <0.0.1 for compatibility with versions of Julia that do not allow upgradable stdlibs.
x-ref https://github.com/JuliaTesting/Aqua.jl/pull/224

Add compat to stdlibs in Project.toml

---

test/MOI_wrapper.jl

Thanks to https://github.com/jump-dev/MathOptInterface.jl/pull/2357 and https://github.com/jump-dev/MathOptInterface.jl/pull/1655

Remove failing tests thanks to new MOI release

---

src/MOI_wrapper/MOI_wrapper.jl

We build OptimizerCache{T} in MOI.optimize!, so we cannot have a different T here.

Remove unreachable code branch

---

src/MOI_wrapper/MOI_wrapper.jl

This is now checked
https://github.com/jump-dev/MathOptInterface.jl/pull/2665
so SCS does not even precompile
```julia
ERROR: LoadError: TypeError: in typeassert, expected Vector{Type}, got a value of type Vector{UnionAll}
Stacktrace:
[1] get(model::MathOptInterface.Utilities.CachingOptimizer{SCS.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, attr::MathOptInterface.Bridges.ListOfNonstandardBridges{Float64})
@ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/yI6C0/src/Utilities/cachingoptimizer.jl:1047
[2] full_bridge_optimizer(model::MathOptInterface.Utilities.CachingOptimizer{SCS.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, ::Type{Float64})
@ MathOptInterface.Bridges …
```

Fix return type of ListOfNonstandardBridges
